CREATE CONSTRAINT collegio_name IF NOT EXISTS ON (c:Collegio) ASSERT c.name IS UNIQUE;
CREATE CONSTRAINT lista_name IF NOT EXISTS ON (l:Lista) ASSERT l.name IS UNIQUE;
CREATE CONSTRAINT persona_uri IF NOT EXISTS ON (p:Persona) ASSERT p.uri IS UNIQUE;
CREATE CONSTRAINT luogo_loc IF NOT EXISTS ON (luogo:Luogo) ASSERT luogo.loc IS UNIQUE;
CREATE CONSTRAINT commissione_name IF NOT EXISTS ON (comm:Commissione) ASSERT comm.name IS UNIQUE;
CREATE CONSTRAINT atto_uri IF NOT EXISTS ON (a:Atto) ASSERT a.uri IS UNIQUE;